steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_}/${_IMAGE_}', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT_}/${_IMAGE_}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'vision-ml-cr', '--image', 'gcr.io/rikudog/vsntest','--allow-unauthenticated', '--region', 'us-central1','--memory', '2G']
images:
- 'gcr.io/${_PROJECT_}/${_IMAGE_}'
